routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('products', 'ProductController');
Route::resource('admin', 'AdminController');
Route::resource('comment', 'CommentController');
Route::resource('contact', 'ContactController');
Route::resource('history', 'HistoryController');

Route::get('cart', 'ProductController@cart');

Route::get('add-to-cart/{id}', 'ProductController@addToCart');

Route::patch('update-cart', 'ProductController@update');

Route::delete('remove-from-cart', 'ProductController@remove');

resources/views/admin/create.blade.php
@extends('layout.admin')
@section('content')
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif
{{ Form::open(['route' => 'admin.store', 'files' => 'true']) }}
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" name="name" id="name" placeholder="Enter Name">
    </div>
    <div class="form-group">
      <label for="price">Price</label>
      <input type="text" class="form-control" name="price" id="price" placeholder="Enter Price">
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <input type="text" class="form-control" id="description" name="description" placeholder="Enter Description">
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">Upload</span>
      </div>

      <div class="custom-file">
        {{-- <input type="file" class="custom-file-input" name="photo" id="photo">
        <label class="custom-file-label" for="photo">Choose file</label> --}}
        {!! Form::file('image', ['class'=>'form-control','placeholder'=>''])!!}
      </div>

    </div><br>


    {{ Form::submit('Create the Product!', ['class' => 'btn btn-primary']) }}
    {{ csrf_field() }}
{{ Form::close() }}
@endsection

resources/views/admin/edit.blade.php
@extends('layout.admin')
@section('content')
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif
  <form method="post" action="{{ route('admin.update', $product->id) }}">
            @method('PATCH')
            @csrf
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" name="name" id="name" value="{{ $product->name }}">
    </div>
    <div class="form-group">
      <label for="price">Price</label>
      <input type="text" class="form-control" name="price" id="price" value="{{ $product->price }}">
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <input type="text" class="form-control" id="description" name="description" value="{{ $product->description }}">
    </div>
    <img src="{{url('/uploads/products/'.$product->image)}}" style="width: 20%; height: 30%;" alt="Image"/>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">Upload</span>
      </div>

      <div class="custom-file">
        {{-- <input type="file" class="custom-file-input" name="photo" id="photo">
        <label class="custom-file-label" for="photo">Choose file</label> --}}
        {!! Form::file('image', ['class'=>'form-control','placeholder'=>''])!!}
      </div>

    </div><br>


    {{ Form::submit('Create the Product!', ['class' => 'btn btn-primary']) }}

{{ Form::close() }}
@endsection

resources/views/admin/index.blade.php
@extends('layout.admin')
@section('content')

<div>
  <a style="margin: 19px;" class="btn btn-primary" href="{{ route('admin.create') }}">New Product</a>
</div>
<div class="col-sm-12">

@if(session()->get('success'))
  <div class="alert alert-success">
    {{ session()->get('success') }}
  </div>
@endif
</div>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Detail</th>
        <td colspan=2>Actions</td>
      </tr>
    </thead>
    <tbody>
      @foreach($products as $data)
      <tr class="products_name text-center">
        <td scope="row">{{ $data->id }}</td>
        <td>{{ $data->name }}</td>
        <td class="products_price text-center">{{ $data->price }}</td>
        <td>{{ $data->description }}</td>
        <td><a href="{{ URL::to('admin/' . $data->id) }}"><img src="{{url('/uploads/products/'.$data->image)}}" style="width: 20%; height: 30%;" alt="Image"/></a></td>
        <td>
                <a href="{{ route('admin.edit',$data->id)}}" class="btn btn-primary">Edit</a>
        </td>
        <td>
                <form action="{{ route('admin.destroy', $data->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
        </td>
      </tr>
        @endforeach
    </tbody>
  </table>

@endsection

resources/views/admin/show.blade.php
@extends('layout.admin')
@section('content')
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
  @endif
<div class="row products_detail_div">
    <!-- Products info -->
    <div class="col-5">
            <!-- Naziv -->
            <h1 class="text-left">{{ $product->name }}</h1>
            <!-- Cena -->
            <p class="text-left">Cena: </p>
            <h3 class="text-left text-warning">{{ $product->price }}</h3>
            <p class="text-left">Opis: </p>
            <p class="text-center">{{ $product->description }}</p>
            <p class="text-left">Slika: </p>
            <p class="text-left"><img src="{{url('/uploads/products/'.$product->image)}}" style="width: 100%; height: 100%;" alt="Image"/></p>
            <!-- linija -->
            <div class="products_line"></div>

    </div>

</div>

<div class="products_comments_div row">
        <div class="col-md-6 col-xs-12">
                <div class="row">
                        <i class="fa fa-comments-o" aria-hidden="true" style="font-size: 200%;"></i>
                        <h3 class="float-left">Comments</h3>
                </div>
                @foreach($comments as $comment)
                  <div class=" shadow-sm product_comment_thumb">
                      <div class="row">
                          <!-- Ime -->
                          <div class="col-6">
                              <p class="font-weight-bold">{{ $comment->name }}</p>
                          </div>
                          <!-- Datum -->
                          <div class="col-6">
                              <p class="text-right">{{ $comment->created_at }}</p>
                          </div>
                          <!-- Comentar -->
                          <div class="col-12 products_comment_text">
                          <p class="text-justify font-weight-light ">{{ $comment->comment }}</p>
                          </div>
                      </div>
                  </div>
                @endforeach
        </div>
  </div>
@endsection